apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
type: Opaque
data:
  # Atenção: Estes valores devem ser convertidos para Base64 no Linux/GitBash
  # Exemplo: echo -n "postgres" | base64 -> cG9zdGdyZXM=
  username: cG9zdGdyZXM=  # user em base64
  password: cG9zdGdyZXM=  # senha em base64